FROM nginx:alpine

# There's a diff in nginx/default files. Will follow recommended guide and use default.conf
# In between each test remember to clear cache.

# COPY nginx.conf /etc/nginx/nginx.conf

COPY default.conf /etc/nginx/conf.d/default.conf